description: "Explore an interactive web application built with Streamlit for visual data exploration of car sales advertisements. This project showcases skills in Python programming, web application development, and data visualization, offering users real-time insights through dynamic and scalable visualizations."
theme: jekyll-theme-cayman
